swipe:
  3:
    left:
      command: "sh /home/victoneux/dotfiles/scripts/screenorient.sh left"
    right:
      command: "sh /home/victoneux/dotfiles/scripts/screenorient.sh right"
    up:
      command: "sh /home/victoneux/dotfiles/scripts/screenorient.sh normal"
    down:
      command: "sh /home/victoneux/dotfiles/scripts/screenorient.sh inverted"
