swaylock \
	--image ~/.config/scripts/wallpaper/lock.png \
	--indicator-radius 30 \
	--indicator-thickness 10 \
	--indicator-idle-visible \
	--ignore-empty-password \
	\
	--inside-color ffffff00 \
	--inside-clear-color ffffff00 \
	--inside-caps-lock-color ffffff00 \
	--inside-wrong-color ffffff00 \
	--line-color 585b70 \
	--line-clear-color 89dceb \
	--line-caps-lock-color 585b70 \
	--line-ver-color 585b70 \
	--line-wrong-color f38ba8 \
	--ring-color 1e1e2e \
	--ring-clear-color 1e1e2e \
	--ring-caps-lock-color 1e1e2e \
	--text-color ffffff00 \
	--text-clear-color ffffff00 \
	--text-caps-lock-color ffffff00 \
	--text-ver-color ffffff00 \
	--text-wrong-color ffffff00 \
	--separator-color 585b70 \
	--bs-hl-color ca9ee6 \
	--caps-lock-bs-hl-color ca9ee6 \
	--caps-lock-key-hl-color a6d189 \
	--key-hl-color a6d189
